version: '3'

services:
  ros-master:
    image: ros:noetic-ros-core
    container_name: ros-master
    command: stdbuf -o L roscore
    network_mode: host
    
  micebot:
    user: root
    depends_on: 
      - ros-master
    image: micebot:windows
    build:
      context: ..
      dockerfile: ./micebot_dockerfiles/Dockerfile.windows
    container_name: micebot
    volumes:
      - "../:/root/catkin_ws/src/"
    privileged: True
    network_mode: host
    tty: True
    stdin_open: True
    command: bash